/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.test.car;

import java.io.IOException;

public class DriverLessApp {
    public static void main(String[] args) throws IOException {
        CarTestConsoleRunner controller = new CarTestConsoleRunner();
        controller.run();
    }
}
